on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: list files before checkout
        run: ls -l -a
      - name: checkout repository
        uses: actions/checkout@v4.3.1
      - name: list files after checkout
        run: ls -l -a
      - name: login on docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.Docker_UserName }}
          password: ${{ secrets.Docker_Passwd }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: briareostm/angular:latest